export const unitDataMap = new Map();

unitDataMap.set('Knight', {
  code: 'kn',
  name: 'Knight',
  shortName: 'Knight',
  ability: 'Sword & Shield',
  power: 22,
  armor: 25,
  health: 50,
  recovery: 1,
  blocking: 80,
  mType: 'path',
  mRadius: 3,
  aType: 'melee',
  aRange: [1, 1],
  tier: 1,
  rarity: 3,
});

unitDataMap.set('Pyromancer', {
  code: 'py',
  name: 'Pyromancer',
  shortName: 'Pyro',
  ability: 'Fire',
  power: 15,
  armor: 0,
  health: 30,
  recovery: 3,
  blocking: 33,
  mType: 'path',
  mRadius: 3,
  aType: 'magic',
  aRange: [0, 3],
  waitFirstTurn: true,
  tier: 1,
  rarity: 13,
});

unitDataMap.set('Scout', {
  code: 'sc',
  name: 'Scout',
  shortName: 'Scout',
  ability: 'Long Shot',
  power: 18,
  armor: 8,
  health: 40,
  recovery: 2,
  blocking: 60,
  mType: 'path',
  mRadius: 4,
  aType: 'melee',
  aRange: [1, 6],
  aLOS: true,
  waitFirstTurn: true,
  tier: 1,
  rarity: 1,
});

unitDataMap.set('Cleric', {
  code: 'cl',
  name: 'Cleric',
  shortName: 'Cleric',
  ability: 'Holy Mass',
  power: 12,
  armor: 0,
  health: 24,
  recovery: 5,
  blocking: 0,
  mType: 'path',
  mRadius: 3,
  aType: 'heal',
  aAll: true,
  tier: 1,
  rarity: 0,
});

unitDataMap.set('BarrierWard', {
  code: 'bw',
  name: 'Barrier Ward',
  shortName: 'BW',
  ability: 'Barrier',
  power: 0,
  armor: 0,
  health: 32,
  recovery: 2,
  blocking: 100,
  mType: false,
  mRadius: 0,
  mPass: false,
  aType: 'barrier',
  aFocus: true,
  aRange: [0, 6],
  directional: false,
  tier: 5,
  rarity: 18,
});

unitDataMap.set('LightningWard', {
  code: 'lw',
  name: 'Lightning Ward',
  shortName: 'LW',
  ability: 'Lightning',
  power: 30,
  armor: 18,
  health: 56,
  recovery: 4,
  blocking: 100,
  mType: false,
  mRadius: 0,
  mPass: false,
  aType: 'magic',
  aRange: [0, 3],
  directional: false,
  tier: 5,
  rarity: 11,
});

unitDataMap.set('DarkMagicWitch', {
  code: 'dmw',
  name: 'Dark Magic Witch',
  shortName: 'DMW',
  keywords: 'witch',
  ability: 'Black Spikes',
  power: 24,
  armor: 0,
  health: 28,
  recovery: 3,
  blocking: 20,
  mType: 'path',
  mRadius: 3,
  aType: 'magic',
  aRange: [1, 4],
  aLinear: true,
  waitFirstTurn: true,
  tier: 1,
  rarity: 12,
});

unitDataMap.set('Assassin', {
  code: 'as',
  name: 'Assassin',
  shortName: 'Sassy',
  ability: 'Multi-Strike',
  specialty: 'Deathblow',
  power: 18,
  armor: 12,
  health: 35,
  recovery: 1,
  blocking: 70,
  mType: 'path',
  mRadius: 4,
  aType: 'melee',
  aRange: [1, 1],
  aAll: true,
  tier: 1,
  rarity: 17,
});

unitDataMap.set('Enchantress', {
  code: 'en',
  name: 'Enchantress',
  shortName: 'Chanty',
  ability: 'Paralytic Field',
  power: 0,
  armor: 0,
  health: 35,
  recovery: 3,
  blocking: 0,
  mType: 'path',
  mRadius: 3,
  aType: 'paralyze',
  aFocus: true,
  aRange: [1, 2],
  aAll: true,
  tier: 1,
  rarity: 17,
});

unitDataMap.set('MudGolem', {
  code: 'mg',
  name: 'Mud Golem',
  shortName: 'Mud',
  ability: 'Punch',
  specialty: 'Quake',
  power: 20,
  armor: 0,
  health: 60,
  recovery: 2,
  blocking: 0,
  mType: 'teleport',
  mRadius: 5,
  aType: 'melee',
  aRange: [1, 1],
  waitFirstTurn: true,
  tier: 2,
  rarity: 8,
});

unitDataMap.set('FrostGolem', {
  code: 'fg',
  name: 'Frost Golem',
  shortName: 'Frosty',
  ability: 'Paralyze',
  power: 0,
  armor: 0,
  health: 60,
  recovery: 2,
  blocking: 0,
  mType: 'path',
  mRadius: 2,
  aType: 'paralyze',
  aFocus: true,
  aRange: [1, 4],
  tier: 2,
  rarity: 9,
});

unitDataMap.set('StoneGolem', {
  code: 'sg',
  name: 'Stone Golem',
  shortName: 'Stone',
  ability: 'Shell',
  power: 0,
  armor: 30,
  health: 60,
  recovery: 4,
  blocking: 0,
  mType: 'path',
  mRadius: 2,
  aType: 'armor',
  aFocus: true,
  aRange: [0, 1],
  tier: 4,
  rarity: 14,
});

unitDataMap.set('DragonTyrant', {
  code: 'dt',
  name: 'Dragon Tyrant',
  shortName: 'DT',
  keywords: [ 'tyrant' ],
  ability: 'Fire Blast',
  power: 28,
  armor: 16,
  health: 68,
  recovery: 3,
  blocking: 40,
  mType: 'teleport',
  mRadius: 4,
  mPass: false,
  aType: 'magic',
  aRange: [1, 3],
  aLOS: true,
  aLinear: true,
  waitFirstTurn: true,
  tier: 3,
  rarity: 6,
});

unitDataMap.set('BeastRider', {
  code: 'br',
  name: 'Beast Rider',
  shortName: 'BR',
  keywords: [ 'beast' ],
  ability: 'Piercing Thrust',
  power: 19,
  armor: 15,
  health: 38,
  recovery: 1,
  blocking: 45,
  mType: 'path',
  mRadius: 4,
  mPass: false,
  aType: 'melee',
  aRange: [1, 2],
  aLinear: true,
  tier: 2,
  rarity: 16,
});

unitDataMap.set('DragonspeakerMage', {
  code: 'dm',
  name:'Dragonspeaker Mage',
  shortName: 'DSM',
  ability: 'Dragon Fire',
  power: 15,
  armor: 0,
  health: 30,
  recovery: 3,
  blocking: 33,
  mType: 'path',
  mRadius: 3,
  aType: 'magic',
  aRange: [0, 3],
  waitFirstTurn: true,
  tier: 4,
  rarity: 9,
});

unitDataMap.set('ChaosSeed', {
  code: 'cs',
  name: 'Chaos Seed',
  shortName: 'Seed',
  ability: 'Chaos',
  specialty: 'Awaken',
  power: 24,
  armor: 95,
  health: 6,
  recovery: 0,
  blocking: 50,
  mType: false,
  mRadius: 0,
  aType: 'magic',
  directional: false,

  baseSprite: 'WyvernEgg',
  imports: ['Lightning','Sparkle'],
  sounds: {
    crack: 'crack',
    attack: 'sprite:core/sounds/sound1370',
    block: 'sprite:core/sounds/sound8',
    heal: 'sprite:core/sounds/sound1203',
    wind: {
      src: 'chaos',
      volume: 0.5,
      sprite: {
        wind1: [   0, 1950],
        wind2: [2150, 1950],
        wind3: [4300, 1800],
        wind4: [6300, 2500],
        wind5: [9000, 1725]
      }
    },
    phase: {
      src: 'sprite:core/sounds/sound4',
      rate: 0.5,
    },
    roar: {
      src: 'chaos',
      sprite: {
        roar: [10925, 1675],
      }
    }
  },
  tier: 5,
});

unitDataMap.set('PoisonWisp', {
  code: 'pw',
  name: 'Poison Wisp',
  shortName: 'Wispy',
  ability: 'Poison',
  power: 4,
  armor: 0,
  health: 30,
  recovery: 2,
  blocking: 0,
  mType: 'teleport',
  mRadius: 6,
  aType: 'poison',
  aRange: [1, 2],
  aAll: true,
  aLinear: true,
  waitFirstTurn: true,
  tier: 3,
  rarity: 11,
});

unitDataMap.set('Furgon', {
  code: 'fu',
  name: 'Furgon',
  shortName: 'Furgy',
  keywords: [ 'furg' ],
  ability: 'Summon Nature',
  specialty: 'Entangle',
  power: 0,
  armor: 0,
  health: 48,
  recovery: 1,
  blocking: 50,
  mType: 'path',
  mRadius: 3,
  aType: 'summon',
  aRange: [0, 2],
  tier: 2,
  rarity: 15,
  features: {
    // Turn this off to enable limited lifetimes for shrubs.
    evergreen: true,
    // Turn this on to enable transform-on-death
    transform: false,
  },
});

unitDataMap.set('Shrub', {
  code: 'sh',
  name: 'Shrub',
  shortName: 'Shrub',
  power: 0,
  armor: 0,
  health: 0,
  lifespan: 3,
  recovery: 0,
  blocking: 0,
  mType: false,
  mPass: false,
  aType: false,
  directional: false,
  tier: 5,
  sounds: {
    block: 'sprite:core/sounds/sound8',
  },
});

unitDataMap.set('Trophy', {
  code: 'tr',
  name: 'Trophy',
  shortName: 'Trophy',
  tier: 5,
  sounds: {
    block: 'sprite:core/sounds/sound8',
  },
});

unitDataMap.set('GolemAmbusher', {
  code: 'ga',
  name: 'Golem Ambusher',
  shortName: 'GA',
  ability: 'Boulder',
  power: 20,
  armor: 0,
  health: 60,
  recovery: 3,
  blocking: 0,
  mType: 'path',
  mRadius: 2,
  aType: 'melee',
  aRange: [4, 5],
  waitFirstTurn: true,
  tier: 3,
  rarity: 17,
});

unitDataMap.set('Berserker', {
  code: 'be',
  name: 'Berserker',
  shortName: 'Berz',
  ability: 'Stun',
  power: 22,
  armor: 0,
  health: 42,
  recovery: 1,
  blocking: 25,
  mType: 'path',
  mRadius: 3,
  mPass: false,
  aType: 'melee',
  aRange: [1, 1],
  tier: 3,
  rarity: 17,
  features: {
    unblockableStun: false,
  },
});

unitDataMap.set('ChaosDragon', {
  code: 'cd',
  name: 'Chaos Dragon',
  shortName: 'CD',
  ability: 'Static Charge',
  specialty: 'Regenerate',
  power:28,
  armor:30,
  health:38,
  recovery:1,
  blocking:50,
  mType: 'teleport',
  mRadius: 4,
  mPass: false,
  aType: 'magic',
  aLOS: true,
  aLinear: true,
  aRange: [1, 3],

  baseSprite: 'DragonTyrant',
  imports: ['Sparkle'],
  sounds: {
    heal: 'sprite:core/sounds/sound1203',
    attack: 'sprite:core/sounds/sound1602',
    charge: { src:'charge', rate:0.6 },
    buzz: { src:'buzz', rate:0.6 },
    phase: { src:'sound4', rate:0.5 },
  },
  // The frames used when hatching
  hatch: [
    ['block', 4],
    ['block', 1],
    ['attack', 3],
    ['block', 0],
    ['attack', 4],
    ['attack', 5],
    ['attack', 4],
    ['stand'],
  ],
  tier: 5,
});

// Map unit type names to IDs until we get rid of the IDs.
export const unitTypeToIdMap = new Map();

[...unitDataMap.keys()].forEach((unitType, unitTypeId) => {
  unitTypeToIdMap.set(unitType, unitTypeId);
});

export const unitTypeByCode = new Map(Array.from(unitDataMap.values()).map(ud => [ ud.code, ud ]));

export default unitDataMap;
